---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-1804
    image: geerlingguy/docker-ubuntu1804-ansible
    pre_build_image: true
  - name: ubuntu-2004
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
  - name: centos-7
    image: geerlingguy/docker-centos7-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
